### ISSUE TITLE
Missing LI's tags in app.html.eex

### ISSUE THREAD

**Issue by Narven** [elixir-elm-tutorial/platform#37]
I think is missing some `<li>` 's in app.html.eex.

None of what is inside of the `<ul>` Contains LI

[https://github.com/elixir-elm-tutorial/platform/blob/a3a837568aee3e64ddd2aba3ead837a8dd610adf/lib/platform_web/templates/layout/app.html.eex#L14](https://github.com/elixir-elm-tutorial/platform/blob/a3a837568aee3e64ddd2aba3ead837a8dd610adf/lib/platform_web/templates/layout/app.html.eex#L14)

**Comment by bijanbwb** [comment]
Looks like you're right, thanks so much for getting in touch.

If I push some updates to the content and demo app I'll be sure to include the `<li>` tags in there.

**Comment by Narven** [comment]
Thanks for an awesome book.
