### ISSUE TITLE
undefined function player_path/3

### ISSUE THREAD

**Issue by oshybrid** [elixir-elm-tutorial/platform#38]
Heds up.

Using...
Erlang 23.1.1
Elixir 1.11.0
Phoenix 1.5.5

Getting this in chapter 4

== Compilation error in file lib/platform_web/views/player_view.ex ==
** (CompileError) lib/platform_web/templates/player/edit.html.eex:3: **undefined function player_path/3**
    (elixir 1.11.0) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

```
<h2>New Player</h2>

<%= form_for @changeset, player_path(@conn, :create), fn f -> %>

	<%= if @changeset.action do %>
		<div class="alert alert-danger">
			<p>Oops, something went wrong! Please check the errors below.</p>
		</div>
	<% end %>

	<div class="form-group">

		<%= label f, :username, "Player Username", class: "control-label" %>
		<%= text_input f, :username, placeholder: "Enter username...", class: "form-control" %>
 		<%= error_tag f, :username %>
 	</div>

 	<div class="form-group">
 		<%= label f, :password, "Player Password", class: "control-label" %>
 		<%= password_input f, :password, placeholder: "Enter password...", class: "form-control" %>
 		<%= error_tag f, :password %>
 	</div>

 	<div class="form-group">
 		<%= submit "Submit", class: "btn btn-primary" %>
 	</div>
 <% end %>

 <span><%= link "Back", to: player_path(@conn, :index) %></span>

```

**Comment by bijanbwb** [comment]
Thanks for the heads up!

I can try running through the content again with the latest versions and make some changes if needed.

Off the top of my head I think `player_path` might need to be `Routes.player_path`.

**Comment by oshybrid** [comment]
I was thinking that too…
But when I checked the book I only saw “player_path” under routing type stuff under the Authentication section I think.
In order of checking the book , you requested that we look at the changes before we get to that part of the book.

Brad

**Comment by oshybrid** [comment]
Any luck?

**Comment by bijanbwb** [comment]
Hey sorry about that. I looked into this and couldn't figure out where the `player_path` might have come from in the content. It looks like all the instances that show up contain `Routes.player_path` as far as I can tell.

Here's a search through the content:
https://github.com/elixir-elm-tutorial/elixir-elm-tutorial-book/search?q=player_path

Is there any chance you're working through an old version of the book? If it's a PDF can you send me the page number?

**Comment by bijanbwb** [comment]
Here's a screenshot of what the content should look like for that New Player form:

<img width="823" alt="Screen Shot 2020-10-16 at 1 15 51 PM" src="https://user-images.githubusercontent.com/201320/96288662-ca254400-0fb1-11eb-9097-045ba7effa09.png">

**Comment by oshybrid** [comment]
This is my page 52...

**Comment by bijanbwb** [comment]
It looks like the screenshot didn't come through with your comment.

Can you send me an email `bijanbwb@gmail.com` so I can send you the latest PDF?
